CREATE PROCEDURE `ADD_WORD_COUNT`(
	BOOK_ID INT
)
BEGIN
	DECLARE NOW_WORD_COUNT INT;
    
  SELECT word_count + 1 INTO NOW_WORD_COUNT FROM book where id = BOOK_ID;
  
	UPDATE book SET word_count = NOW_WORD_COUNT where id = BOOK_ID;
END




CREATE PROCEDURE `PLUS_WORD_COUNT`(
	BOOK_ID INT
)
BEGIN
	DECLARE NOW_WORD_COUNT INT;
    
    SELECT word_count + 1 INTO NOW_WORD_COUNT FROM book where id = BOOK_ID;
    
	UPDATE book SET word_count = NOW_WORD_COUNT where id = BOOK_ID;
END



CREATE PROCEDURE `UPDATE_WORD_COUNT`(
	BOOK_ID INT,
    WORD_COUNT INT
)
BEGIN
	UPDATE book SET word_count = WORD_COUNT where id = BOOK_ID;
END