name: updateTest

on:
  push:
    branches:
      - 'develop'  # 개발 브랜치가 푸쉬되었을 때 동작

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }} # 서버  ip주소
          username: ${{ secrets.TEST_USERNAME }} # 서버 유저이름
          key: ${{ secrets.TEST_SSH_KEY }} # AWS 연결 키
          sudo: true
          port: ${{ secrets.TEST_PORT }} # 서버 포트
          script: ./update.sh
